---
- name: Demo filter
  hosts: all
  vars:
    URL: https://github.com/zelar-soft-roboshop/frontend/archive/main.zip
    tag_data:
      Environment: dev
      Application: Payment
  tasks:
    - name: URL Splits
      debug:
        msg: "{{ URL | urlsplit }}"   
    - name: URL Splits Print column
      debug:
        msg: "{{ URL.split('/') | last }}" 
    - name: Print tag data
      debug:
        msg: "{{ tag_data |dict2items }}" 

    - name: Create servers
      debug:
        name: "{{ item.name }}"
        state: present
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
        - name: server2
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
      # loop_control:
      #   label: "{{ item.name }}"

