---
- name: loop example
  hosts: all
  tasks:    
    - name: Create servers
      debug:
        msg: "{{ item.name }}"
        # state: present
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
        - name: server2
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
      # loop_control:
      #   label: "{{ item.name }}"

