- name: Varible 
  hosts: all
  vars: 
    url: playbooks.com
    company: zelarsoft
  vars_files:
  - example-var.yml
  vars_prompt:
    - name: url
      prompt: Enter Url  
  tasks:
  - name: Print url
    debug:
      msg: my url is {{ url }} and from company {{ company }}
  - name: Print url
    debug:
      msg: my url is {{ url }} and from company {{ company }} 
    vars:
      company: lakshmoji       
  - name: Basic System env Vars
    debug:
      msg: "'{{ lookup('env', 'HOME') }}' is the HOME environment variable." 
  - name: Basic System Hostname
    shell:
      cmd: hostname
      #msg: "'{{ lookup('env', 'HOSTNAME') }}' is the hostname environment variable."      
