- name: Varible 
  hosts: all
  vars: 
    url: playbooks.com
    company: zelarsoft
  tasks:
  - name: Print url
    debug:
      msg: my url is {{ url }} and from company {{ company }}
  - name: Basic System env Vars
    debug:
      msg: "'{{ lookup('env', 'HOME') }}' is the HOME environment variable." 
  - name: Basic System Hostname
    shell:
      cmd : hostname
      #msg: "'{{ lookup('env', 'HOSTNAME') }}' is the hostname environment variable."      
